name: diario as - selenium
# run-name: selenium - ${{ inputs.os }} - ${{ inputs.browser }}
run-name: selenium - ubuntu-latest - ${{ inputs.browser }}

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Elige el navegador
        required: true
        options:
          - chrome
          - safari
          - firefox
      allure:
        type: boolean
        description: Publicar en Allure
        default: true
      extent:
        type: boolean
        description: Generar reporte Extent
        default: true
      pdf:
        type: boolean
        description: Generar PDF
        default: true
      recorder:
        type: boolean
        description: Grabar la ejecución
        default: true

jobs:
  selenium:
    # runs-on: ${{ github.event.inputs.os }}
    # runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Generate artifact for ExtentReports Spark HTML
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.extent == 'true' }}
        with:
          name: report_html
          path: ./extent-reports/spark

      - name: Generate artifact for Allure Reports
        uses: actions/upload-artifact@v3
        if: ${{ github.event.inputs.allure == 'true' }}
        with:
          name: report_allure
          path: ./allure-results

  allure:
    needs: selenium
    if: ${{ github.event.inputs.allure == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: report_allure
          path: ./allure-results

      - name: Download Artifact 2
        uses: actions/download-artifact@v3
        with:
          name: report_html
          path: ./extent-spark



      - name: Get AllureReports history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: ./reports/chrome-desktop/allure

      - name: Get AllureReports results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: ./reports/chrome-desktop/allure/allure-history
          keep_reports: 10

      - name: Prepare AllureReports deploy to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./reports/chrome-desktop/allure/allure-history